# Generated by Django 4.2.7 on 2023-12-20 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NumberPlate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_text', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='number_plates/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
