# Generated by Django 4.2.7 on 2023-12-21 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='numberplate',
            name='plate_text',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
