# Generated by Django 4.2.7 on 2023-12-21 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_numberplate_plate_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='numberplate',
            name='image',
            field=models.ImageField(upload_to='number_plate/'),
        ),
    ]
