# Generated by Django 4.2.7 on 2023-12-24 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_numberplate_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='NumberPlate2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='videos/')),
            ],
        ),
    ]
